---
- name: Install dependencies
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - gcc
    - libcurl-devel

- name: Add gpg key for td-agent
  rpm_key:
    key: "https://packages.treasuredata.com/GPG-KEY-td-agent"

- name: Add repository for td-agent
  yum_repository:
    name: TreasureData
    description: "treasuredata"
    baseurl: 'http://packages.treasuredata.com/2/redhat/\$releasever/\$basearch'
    enabled: yes
    gpgcheck: yes

- name: Install td-agent
  yum:
    name: td-agent
    state: latest

- name: Create conf directory
  file:
    path: "{{ tdagent_confpath }}/conf.d"
    state: directory

- name: Upload td-agent.conf
  template:
    src: td-agent.conf.j2
    dest: "{{ tdagent_confpath }}/td-agent.conf"

- name: start tdagent
  systemd:
    name: td-agent
    state: started
    enabled: yes
