---
- name: Install ruby for gem 
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - ruby
    - ruby-dev

- name: Install fluentd
  gem:
    name: "{{ item }}"
    state: latest
    user_install: no
  with_items:
    - fluentd

- name: Create log directory
  file:
    path: /var/log/fluentd
    state: directory
    mode: 0777

- name: create conf directory
  file:
    path: "{{ fluentd_confpath }}/conf.d"
    state: directory
    mode: 0755
    recurse: yes

- name: Check if config file exists
  stat:
    path: "{{ fluentd_confpath }}/fluent.conf"
  register: _config

- name: Initialize fluentd
  shell: /bin/bash -lc "fluentd -s {{ fluentd_confpath }}"
  when: not _config.stat.exists  

- name: Upload fluent.conf
  template:
    src: fluent.conf.j2
    dest: "{{ fluentd_confpath }}/fluent.conf"

- name: start fluentd
  shell: /bin/bash -lc "fluentd -c {{ fluentd_confpath }}/fluent.conf &"
  register: _result
